import { createTheme } from '@mui/material/styles';

export const theme = createTheme({
  palette: {
    mode: "dark",
    primary: {
      main: '#ffffff',
    },
    secondary: {
      main: '#b9f6ca',
    },
  }
});

export const backgroundJSONOptions = {
  // Fall
  "Autumn Forest": "https://www.youtube.com/watch?v=IadsLclBOS8",
  "Peaceful Autumn Day At Hogwarts": "https://www.youtube.com/watch?v=xyyMe8qZE8E",
  "Fall Coffee Shop": "https://www.youtube.com/watch?v=VMAPTo7RVCo&t=1287s7",
  "Halloween Party": "https://www.youtube.com/watch?v=LmCg6V8e8Jw&t=42s",
  "Halloween Porch": "https://www.youtube.com/watch?v=cykFvQ2Y8sM&t=55s",
  "Autumn at Hogwarts": "https://www.youtube.com/watch?v=LYMAex9lSXA",
  "Fall Grounds at Hogwarts": "https://www.youtube.com/watch?v=YpF6N-tL70Y",
  "Magic Kingdom Halloween": "https://www.youtube.com/watch?v=CYGAXigR_Z8",
  "Nighttime Porch": "https://www.youtube.com/watch?v=-gKvayYQVcg",
  "Autumn Fly Over": 'https://www.youtube.com/watch?v=szRyk93Lx4E',
  "Witch's Kitchen": "https://www.youtube.com/watch?v=900GFG30Fzg",
  "Halloween at Hogwarts": "https://www.youtube.com/watch?v=pCRAnf1UCLA",
  "Hogwarts Forest": "https://www.youtube.com/watch?v=6t44YRHSF1Q",
  "Rainy Castle": "https://www.youtube.com/watch?v=l1_NvzdbewI",
  "Stormy Night by the Sea": "https://www.youtube.com/watch?v=qkR8ANcettQ",
  // Winter
  "Christmas at Hogwarts - Walking": "https://www.youtube.com/watch?v=sSBUL1INwYw",
 
  "Winter Cabin": "https://www.youtube.com/watch?v=PXpERbbAvBs",
  "Winter Cabin - Jazz": "https://www.youtube.com/watch?v=F3vSEKruRJc",
  "Christmas Porch": "https://youtu.be/hQXOYApD-Rs?t=2349",
  "Instrumental Christmas": "https://www.youtube.com/watch?v=6toYzO9spWE",
  "Calm Winter Day at Hogwarts": "https://www.youtube.com/watch?v=yWkHBpTXb1E",
  "Magic Kingdom Christmas": "https://www.youtube.com/watch?v=WXccs2azATQ",
  "Magic Kingdom Christmas 2": "https://www.youtube.com/watch?v=t4GSiJx6Glo",
  "Winter Ambience Drone Flyover": "https://www.youtube.com/watch?v=CUIdMusnugs",
 
  "The Yule Ball": "https://www.youtube.com/watch?v=tTfr-0qa3OQ",
  "Winter Chalet": "https://www.youtube.com/watch?v=111hKC_4LuY&t=234s",
  "Winter Coffee Shop": "https://www.youtube.com/watch?v=twM7ulKpPjI&t=323s",
  "Winter Forest Walkthrough": "https://www.youtube.com/watch?v=OIQwYWRlXOY",
  // Spring
  
  "EPCOT Flower Garden Festival": "https://www.youtube.com/watch?v=seAjL2U6N6o",
  "English Forest": "https://www.youtube.com/watch?v=IsPBplWLImI",
  "Greek Seaside": "https://www.youtube.com/watch?v=iZkO0wn72ys",
  "Hogwarts Spring Walkthrough": "https://www.youtube.com/watch?v=GybMO_-77Xw",
  "Mountain View": "https://youtu.be/qRTVg8HHzUo?t=22",
  "Spring Cafe 1": "https://www.youtube.com/watch?v=hoX_NS0htBQ",
  "Spring Cafe 2": "https://www.youtube.com/watch?v=-aL6ig2lxrE",
 
  "Sunflower Meadow": "https://youtu.be/ipf7ifVSeDU?t=6",
  // Summer
  "Aulani": "https://www.youtube.com/watch?v=pmW5gjbCggM",
  "Beach Bonfire": "https://youtu.be/Y1y9GAjuSt8?t=24",
  "Flying Over Hawaii": "https://www.youtube.com/watch?v=J_4leOeH9Lc",
  "Hawaiian Sunset": "https://www.youtube.com/watch?v=0ANLBX2EgmM",
 

  "Sea Turtles in Hawaii": "https://www.youtube.com/watch?v=yLuEx-XH3Uc&t=530s",
  "Summer Night": "https://www.youtube.com/watch?v=SN3xlcjbvUo&t=164s",
 
  "Summer Day at Hogwarts": "https://www.youtube.com/watch?v=CNw2r93p6xE",
  "Summer Picnic": "https://www.youtube.com/watch?v=w6n7xzjMkI4",
  "Tropical Beach": "https://www.youtube.com/watch?v=DGIXT7ce3vQ",
  "Waterfall": "https://www.youtube.com/watch?v=V1RPi2MYptM",
  // Disney
  "Animal Kingdom Walkthrough": "https://www.youtube.com/watch?v=X611cw3plh8",
  "California Adventure Walkthrough": "https://www.youtube.com/watch?v=rAYNdyKBJ3w",
  "Disney's Coral Reef": "https://youtu.be/JxiB4y43uN8?t=139",
  "Disneyland Paris Walkthrough": "https://www.youtube.com/watch?v=ALXKzjfWj8E",
  "Disneyland Walkthrough": "https://www.youtube.com/watch?v=-CMu6_7EZS8",
  "Disney Springs": "https://youtu.be/Szetlwwd6jw?t=42",
  "Disney Springs Walkthrough": "https://www.youtube.com/watch?v=g1CdYGzWESY",
  "Encanto": "https://youtu.be/eeorll3-Ugw?t=11",
  "Kiss Goodnight": "https://www.youtube.com/watch?v=QqGjuloQGgo",
  "Magic Kingdom Walkthrough": "https://www.youtube.com/watch?v=JsCxsiGYf98",
  "Magic Kingdom Sunset": "https://www.youtube.com/watch?v=EoZCMGPtZlM",
  "EPCOT Walkthrough": "https://www.youtube.com/watch?v=f0pI0jjiMAw",
  "Hollywood Studios Walkthrough": "https://www.youtube.com/watch?v=qf_3QFDHMrY",
  "Living With the Land": "https://www.youtube.com/watch?v=cH-OKXk9Gyo",
   "Moana: Journey of Water": "https://www.youtube.com/watch?v=CGsZwJJtebk",
   "Tokyo Disneyland Walkthrough": "https://www.youtube.com/watch?v=4tMqnTiqHhU",
   "Tokyo DisneySea Walkthrough": "https://www.youtube.com/watch?v=h0LwJxYQcY4",
  // Harry Potter
  "Christmas Great Hall": "https://youtu.be/_v4cgUVBsi4?t=60",
  "Diagon Alley Night": "https://www.youtube.com/watch?v=v0haKQUgxYE",
  "Hogwarts Express": "https://youtu.be/daCu-ku1v8E?t=141",
  "Hogwarts Library": "https://www.youtube.com/watch?v=20XE6GM7xWo",
  "Hogwarts Library 2": "https://youtu.be/oI9bqFUBJ9E?t=28",
  "Potions Class": "https://www.youtube.com/watch?v=J8K3nPP4V-Y",
  "Weasley's Wizard Wheezes": "https://www.youtube.com/watch?v=WxB6hbba8cY",
  // Other
  "Aquarium": "https://www.youtube.com/watch?v=dBsicD0ItD0",
  "Coral Reef": "https://www.youtube.com/watch?v=tADnCEpbPI8",
  "Redwood Forest Soundscape": "https://www.youtube.com/watch?v=q9rQTB_Qr0A",
  "Train Ride": "https://www.youtube.com/watch?v=Cec4Z-Vlf7Q",
  // Travel
  "Italy Flyover": "https://www.youtube.com/watch?v=tvAZeKhsnOo",
  "Greek Islands Flyover": "https://www.youtube.com/watch?v=VWNnbEatODk",
  "Japan Cherry Blossom Walking Tour": "https://www.youtube.com/watch?v=Q3R9bNrDPzk",
  "British Isles Flyover": "https://www.youtube.com/watch?v=rzr0W1l98Rw",
  "Canada Flyover": "https://www.youtube.com/watch?v=NAIfmFNitF0",
  "Norway Flyover": "https://www.youtube.com/watch?v=ftlvreFtA2A",
  // DCL
  "Alaska 7 Night - Disney Wonder": "youtube.com/watch?v=Q2JZ7idPwx0",
  "Bahamas 3 Night - Disney Wish": "https://www.youtube.com/watch?v=IZw-0y8CG2o",
  "Norway 12 Night - Disney Dream": "https://www.youtube.com/watch?v=IUHsXBoJb0I",
  "Mediterranean 7 Night - Disney Dream": "https://www.youtube.com/watch?v=ZDvqOoxDLV4",
  "Panama Canal 14 Night - Disney Magic": "https://www.youtube.com/watch?v=nG1NLzwURME",
  "Transatlantic 13 Night - Disney Magic": "https://www.youtube.com/watch?v=41d5NPLNP_c"
};

export const backgroundOptions = [
  {
    value: "Fall",
    children: [
      "Autumn at Hogwarts",
      "Autumn Fly Over",
      "Autumn Forest",
      "Fall Coffee Shop",
      "Fall Grounds at Hogwarts",
      "Halloween at Hogwarts",
      "Halloween Party",
      "Halloween Porch",
      "Hogwarts Forest",
      "Magic Kingdom Halloween",
      "Nighttime Porch",
      "Peaceful Autumn Day At Hogwarts",
      "Rainy Castle",
      "Stormy Night by the Sea",
      "Witch's Kitchen",
    ],
  }, {
    value: "Winter",
    children: [
      "Calm Winter Day at Hogwarts",
      "Christmas at Hogwarts - Walking",
      "Christmas Great Hall",
      "Christmas Porch",
      "Instrumental Christmas",
      "Magic Kingdom Christmas",
      "Magic Kingdom Christmas 2",
      "The Yule Ball",
      "Winter Ambience Drone Flyover",
      "Winter Cabin",
      "Winter Cabin - Jazz",
      "Winter Chalet",
      "Winter Coffee Shop",
      "Winter Forest Walkthrough",
    ],
  }, {
    value: "Spring",
    children: [
      "English Forest",
      "EPCOT Flower Garden Festival",
      "Greek Seaside",
      "Hogwarts Spring Walkthrough",
      "Japan Cherry Blossom Walking Tour",
      "Mountain View",
      "Spring Cafe 1",
      "Spring Cafe 2",
      "Sunflower Meadow",
    ],
  }, {
    value: "Summer",
    children: [
      "Aulani",
      "Beach Bonfire",
      "Flying Over Hawaii",
      "Hawaiian Sunset",
      "Sea Turtles in Hawaii",
      "Summer Day at Hogwarts",
      "Summer Night",
      "Summer Picnic",
      "Tropical Beach",
      "Waterfall",
    ],
  }, {
    value: "Disney Cruise Line",
    children: [
      "Alaska 7 Night - Disney Wonder",
      "Bahamas 3 Night - Disney Wish",
      "Mediterranean 7 Night - Disney Dream",
      "Norway 12 Night - Disney Dream",
      "Panama Canal 14 Night - Disney Magic",
      "Transatlantic 13 Night - Disney Magic"
    ],
  }, {
    value: "Disney Parks",
    children: [
      "Animal Kingdom Walkthrough",
      "Aulani",
      "California Adventure Walkthrough",
      "Disney Springs",
      "Disney Springs Walkthrough",
      "Disney's Coral Reef",
      "Disneyland Paris Walkthrough",
      "Disneyland Walkthrough",
      "Encanto",
      "EPCOT Flower Garden Festival",
      "EPCOT Walkthrough",
      "Hollywood Studios Walkthrough",
      "Kiss Goodnight",
      "Living With the Land",
      "Magic Kingdom Christmas",
      "Magic Kingdom Christmas 2",
      "Magic Kingdom Halloween",
      "Magic Kingdom Sunset",
      "Magic Kingdom Walkthrough",
      "Moana: Journey of Water",
      "Tokyo Disneyland Walkthrough",
      "Tokyo DisneySea Walkthrough",
    ],
  }, {
    value: "Harry Potter",
    children: [
      "Autumn at Hogwarts",
      "Calm Winter Day at Hogwarts",
      "Christmas at Hogwarts - Walking",
      "Christmas Great Hall",
      "Diagon Alley Night",
      "Halloween at Hogwarts",
      "Hogwarts Express",
      "Hogwarts Forest",
      "Hogwarts Library",
      "Hogwarts Library 2",
      "Hogwarts Spring Walkthrough",
      "Peaceful Autumn Day At Hogwarts",
      "Potions Class",
      "Summer Day at Hogwarts",
      "The Yule Ball",
      "Weasley's Wizard Wheezes",
    ],
  }, {
    value: "Travel",
    children: [
      "British Isles Flyover",
      "Canada Flyover",
      "Greek Islands Flyover",
      "Greek Seaside",
      "Italy Flyover",
      "Japan Cherry Blossom Walking Tour",
      "Norway Flyover"
    ],
  }, {
    value: "Other",
    children: [
      "Aquarium",
      "Coral Reef",
      "Redwood Forest Soundscape",
      "Train Ride"
    ],
  }
];

export const BASESOUND = 'Base Sound';

export const soundOptions = [
  BASESOUND,
  "Bamboo Forest",
  "Blizzard",
  "Cafe Jazz & Rain",
  "Campfire & River",
  "Christmas Music",
  "Disney Parks Soundscape",
  "Disney Piano",
  "Disney Piano 2",
  "Disney Springs",
  "EPCOT Area Music",
  "Fall Leaves",
  "Fireplace",
  "Forest Sounds",
  "Haunted Mansion Soundscape",
  "Hollywood Studios Area Music",
  "Jungle Sounds",
  "Large Waterfall",
  "Light Rain",
  "Light Snow",
  "Lilo & Stitch Soundscape",
  "Lion King Soundscape",
  "Little Mermaid Soundscape",
  "Magic Kingdom Area Music",
  "Narnia Winter Music",
  "Nighttime Forest",
  "Seaside Piano",
  "Small Waterfall",
  "Snow & Wind",
  "Soft Waves",
  "Stream",
  "Summer Night",
  "Thunder",
  "Tropical House",
  "Waves",
  "WDW Today Channel",
  "Wind",
  "Winter at Hogwarts",
  "Wizarding World Area Music"
];